#
# Retrieve interface details
#
---
- name: "Fetch interfaces"
  ntc_show_command:
    command: "show interface"
    connection: "offline"
    file: "{{ playbook_dir }}/outputs/{{ inventory_hostname }}/show_interface.txt"
    template_dir: "{{ playbook_dir }}/ntc-templates"
    platform: "{{ platforms[ansible_network_os] }}"
  register: interfaces
  tags: ['fetch', 'fetch-interfaces']

- copy:
    content: "{{ interfaces.response | to_nice_yaml(indent=2) }}"
    dest: "{{ host_results }}/interfaces-{{mcast_group}}.yaml"
  tags: ['fetch', 'fetch-interfaces']
