#
# Retrieve lag details
#
---
- name: "Fetch lag"
  ntc_show_command:
    connection: "offline"
    file: "{{ playbook_dir }}/outputs/{{ inventory_hostname }}/show_port-channel_summary.txt"
    command: "show port-channel summary"
    template_dir: "{{ inventory_dir }}/ntc-templates"
    platform: "{{ platforms[ansible_network_os] }}"
  register: lags
  tags: ['fetch', 'fetch-lags']

- copy:
    content: "{{ lags.response|to_nice_yaml(indent=2) }}"
    dest: "{{ host_results }}/lags-{{mcast_group}}.yaml"
  tags: ['fetch', 'fetch-lags']
