#
# Retrieve multicast routing table entries
#
---
- name: "Fetch multicast routes"
  ntc_show_command:
    command: "show ip mroute {{ mcast_group }}"
    connection: "offline"
    file: "{{ playbook_dir }}/outputs/{{ inventory_hostname }}/show_ip_mroute_{{ mcast_group }}_vrf_{{ vrf }}.txt"
    template_dir: "{{ inventory_dir }}/ntc-templates"
    platform: "{{ platforms[ansible_network_os] }}"
  register: mroute
  tags: ['fetch', 'fetch-mroutes']

- copy:
    content: "{{ mroute.response|to_nice_yaml(indent=2) }}"
    dest: "{{ host_results }}/mroutes-{{mcast_group}}.yaml"
  tags: ['fetch', 'fetch-mroutes']
