#
# Retrieve RP
#
---
- name: "Fetch RP"
  ntc_show_command:
    command: "show ip pim rp {{ mcast_group }}"
    connection: "offline"
    file: "{{ playbook_dir }}/outputs/{{ inventory_hostname }}/show_ip_pim_rp_{{ mcast_group }}_vrf_{{ vrf }}.txt"
    template_dir: "{{ inventory_dir }}/ntc-templates"
    platform: "{{ platforms[ansible_network_os] }}"
  register: rp
  tags: ['fetch-rp']

- copy:
    content: "{{ rp.response|to_nice_yaml(indent=2) }}"
    dest: "{{ host_results }}/rp-{{mcast_group}}.yaml"
  tags: ['fetch-rp']

# vim: set ts=2 shiftwidth=2 expandtab:
