#
# Retrieve igmp snooping entries
#
---
- name: "Fetch IGMP Snooping entries"
  ntc_show_command:
    command: "show ip igmp snooping groups {{ mcast_group }}"
    connection: "offline"
    file: "{{ playbook_dir }}/outputs/{{ inventory_hostname }}/show_ip_igmp_snooping_groups_{{ mcast_group }}.txt"
    template_dir: "{{ inventory_dir }}/ntc-templates"
    platform: "{{ platforms[ansible_network_os] }}"
  register: snooping
  tags: ['fetch', 'fetch-snooping']

- copy:
    content: "{{ snooping.response|to_nice_yaml(indent=2) }}"
    dest: "{{ host_results }}/snooping-{{mcast_group}}.yaml"
  tags: ['fetch', 'fetch-snooping']
